services:
  - type: web
    name: fog-ia-detection
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    pythonVersion: 3.12.3
